SELECT *
FROM COVIDDEATHS
ORDER BY 3,4

SELECT *
FROM COVIDVACCINATION
WHERE CONTINENT IS NOT NULL
ORDER BY 3,4

SELECT LOCATION, DATE, TOTAL_CASES, NEW_CASES, TOTAL_DEATHS, POPULATION
FROM COVIDDEATHS
ORDER BY 1,2

--LOOKING AT TOTAL CASES AND TOTAL DEATHS IN NIGERIA 


SELECT LOCATION, DATE, TOTAL_CASES, TOTAL_DEATHS
FROM COVIDDEATHS
WHERE LOCATION LIKE '%NIGERIA%'
ORDER BY 1,2

--LOOKING AT TOTAL CASES VS POPULATION

SELECT LOCATION, DATE, TOTAL_CASES, population, (total_cases/population)*100 AS CASEPERCENTAGE 
FROM COVIDDEATHS
WHERE LOCATION LIKE '%NIGERIA%'
ORDER BY 1,2

--LOOKING AT COUNTRIES WITH THE HIGHEST INFECTION RATE COMPARED TO POPULATION

SELECT LOCATION, population, MAX(TOTAL_CASES) AS HIGHESTINFECTIONCOUNTRIES, MAX((total_cases/population))*100 AS CASEPERCENTAGE
FROM COVIDDEATHS
--WHERE LOCATION LIKE '%NIGERIA%'
GROUP BY LOCATION,POPULATION
ORDER BY CASEPERCENTAGE DESC

--SHOWING COUNTRIES WITH THE HIGHEST DEATH COUNT PER POPULATION

SELECT LOCATION, MAX(CAST (TOTAL_CASES AS INT)) AS TOTALDEATHCOUNT
FROM COVIDDEATHS
--WHERE LOCATION LIKE '%NIGERIA%'
WHERE CONTINENT IS NOT NULL
GROUP BY LOCATION
ORDER BY TOTALDEATHCOUNT DESC

--BREAKING THINGS DOWN BY CONTINENT

SELECT CONTINENT, MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT
FROM COVIDDEATHS
WHERE CONTINENT IS NOT NULL
GROUP BY CONTINENT 
ORDER BY TOTALDEATHCOUNT DESC

--SHOWING CONTINENTS WITH THE HIGHEST DEATH COUNT PER POPULATION

SELECT CONTINENT, MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT
FROM COVIDDEATHS
WHERE CONTINENT IS NOT NULL
GROUP BY CONTINENT 
ORDER BY TOTALDEATHCOUNT DESC

--LOOKING AT TOTAL POPULATION VS VACCINATION


SELECT DEA.continent, DEA.location, DEA.DATE, DEA.POPULATION, VAC.new_vaccinations, SUM (CONVERT(INT, VAC.NEW_VACCINATIONS)) OVER (PARTITION BY DEA.LOCATION)
FROM COVIDDEATHS DEA
JOIN COVIDVACCINATION VAC
ON DEA.LOCATION = VAC.LOCATION
AND DEA.DATE = VAC.DATE 
WHERE DEA.CONTINENT IS NOT NULL
ORDER BY 2,3




